---
version: '3.8'
services:
    mydb:
      image: postgres
      environment:
         POSTGRES_PASSWORD: 43129
    myadminer:
      image: adminer
      ports:
        - 8080:8080
networks:
  default:
   external:
     name: RM
...
