version: '3.8'
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 43129
  apache:
    image: httpd
    ports:
      - 8080:80
    links:
      - mydb
  myphp:
      image: php:7.2-apache
      ports:
        - 7070:80
      links:
        - mydb
        - apache


